##################################
###   KITTY COLORS - MATUGEN   ###
##################################


cursor            #ffb4a8
cursor_text_color #561e16

foreground            #f1dfdc
background            #140c0b
selection_foreground  #442925
selection_background  #e7bdb6
url_color             #e7bdb6

#: black 000000 767676
color0  #1a1110
color8  #3d3230
#: red cc0403 f2201f
color1  #000000
color9  #942300
#: green 19cb00 23fd00
color2  #e7bdb6
color10 #ffdad4
#: yellow cecb00 fffd00
color3  #dec48c
color11 #fbdfa6
#: blue 0d73cc 1a8fff
color4  #73342a
color12 #ffb4a8
#: magenta cb1ed1 fd28ff
color5  #5d3f3b
color13 #e7bdb6
#: cyan 0dcdcd 14ffff
color6  #564419
color14 #dec48c
#: white dddddd ffffff
color7  #d8c2be
color15 #f1dfdc

mark1_foreground #3a0905
mark1_background #ffdad4
mark2_foreground #2c1512
mark2_background #ffdad4
mark3_foreground #251a00
mark3_background #fbdfa6

active_tab_foreground #561e16
active_tab_background #ffb4a8
inactive_tab_foreground #ffdad4
inactive_tab_background #73342a

active_border_color #ffb4a8
inactive_border_color #561e16
# bell_border_color #ff5a00

