####################
###   KEYBINDS   ###
####################


map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+r load_config_file

map ctrl+page_up previous_tab
map ctrl+page_down next_tab

