##################################
###   DUNST COLORS - MATUGEN   ###
##################################


[global]
background	= "{{ colors.surface_container_lowest.dark.hex }}"
highlight	= "{{ base16.base08.dark.hex | lighten: 10.0 }}"

frame_color	= "{{ base16.base08.dark.hex | lighten: 10.0 }}"
separator_color = frame

[urgency_low]
#background = "{{ colors.surface_container_lowest.dark.hex }}"
foreground = "#cdd6f4"

[urgency_normal]
#background = "{{ colors.surface_container_lowest.dark.hex }}"
foreground = "#cdd6f4"

[urgency_critical]
#foreground = "{{ base16.base08.dark.hex | lighten: 10.0 }}"
frame_color = "{{ base16.base08.dark.hex | lighten: 10.0 }}"


