##################################
###   DUNST COLORS - MATUGEN   ###
##################################


[global]
background	= "#140c0a"
highlight	= "#e5736c"

frame_color	= "#e5736c"
separator_color = frame

[urgency_low]
#background = "#140c0a"
foreground = "#cdd6f4"

[urgency_normal]
#background = "#140c0a"
foreground = "#cdd6f4"

[urgency_critical]
#foreground = "#e5736c"
frame_color = "#e5736c"


