##################################
###   DUNST COLORS - MATUGEN   ###
##################################


[global]
background	= "#140c0b"
highlight	= "#942300"

frame_color	= "#942300"
separator_color = frame

[urgency_low]
#background = "#140c0b"
foreground = "#cdd6f4"

[urgency_normal]
#background = "#140c0b"
foreground = "#cdd6f4"

[urgency_critical]
#foreground = "#942300"
frame_color = "#942300"


