###################################
###   FUZZEL COLORS - MATUGEN   ###
###################################


[colors]
background=181115dd
text=eddfe4ff
match=fab1d9ff
selection-match=511d3eff
selection=3b3236dd
selection-text=eddfe4ff
border=9c8d93ff


