###################################
###   FUZZEL COLORS - MATUGEN   ###
###################################


[colors]
background=1a1110dd
text=f1dfdcff
match=ffb4a8ff
selection-match=561e16ff
selection=3d3230dd
selection-text=f1dfdcff
border=a08c89ff


