###################################
###   FUZZEL COLORS - MATUGEN   ###
###################################


[colors]
background=1a110fdd
text=f1dfdbff
match=ffb4a3ff
selection-match=561f12ff
selection=3d3230dd
selection-text=f1dfdbff
border=a08c88ff


