######################################
###  CUSTOMIZED HYPRLAND CONFIG.   ###
######################################


# This configuration was splited into multiple files

# See the wiki for help
# https://wiki.hypr.land/Configuring/

source = ./system/appearance/colorscheme.conf
source = ./system/appearance/layout.conf
source = ./system/appearance/window_rules.conf

source = ./system/config/env.conf
source = ./system/config/permissions.conf
source = ./system/config/autostart.conf
source = ./system/config/keybinds.conf

source = ./system/io/output.conf
source = ./system/io/input.conf


