####################
###   HYPRIDLE   ###
####################


# Prevent double lock
general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Dim the screen
listener {
    timeout = 180 
    on-timeout = brightnessctl -s set 30%-
    on-resume = brightnessctl -r
}

# Lock screen
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Turn off monitors
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}

