#####################
###   AUTOSTART   ###
####################


# Only on startup #
exec-once = waybar
exec-once = awww-daemon
exec-once = hypridle

# Always #
exec = awww img "$HOME/wallpapers/current_wallpaper" --transition-type grow


