##############################
###   APPEARANCE - DUNST   ###
##############################


[global]
font = JetBrains Mono Nerd 13

padding = 10
horizontal_padding = 12

corner_radius = 3
progress_bar_corner_radius = 3

