#################################
###   FUZZEL MENU - EXAMPLE   ###
#################################


# Include general config
include=~/.config/fuzzel/fuzzel.ini


# Add/Override elements #

#prompt="( ^o^)   "
#message="Example menu"
#match-counter=yes
#exit-on-keyboard-focus-loss=no


