#################################
###   FUZZEL MENU - EXAMPLE   ###
#################################


# Include general config
include=~/.config/fuzzel/fuzzel.ini


# Add/Override elements #
[main]
message="󰤄  Idle Options"
#match-counter=yes
minimal-lines=yes
hide-prompt=yes
#prompt=""

