###################################
###   FUZZEL MENU - META MENU   ###
###################################


# Include general config
include=~/.config/fuzzel/fuzzel.ini


# Add/Override elements #
[main]
message="󰍜  Fuzzel Menus"
match-counter=yes
#minimal-lines=yes
hide-prompt=yes
#prompt=""

