###############################
###   FUZZEL MENU - POWER   ###
###############################


# Include general config
include=~/.config/fuzzel/fuzzel.ini


# Add/Override elements #
[main]
message="  - Power Options"
hide-prompt=yes
match-counter=yes
minimal-lines=yes

