###################################
###   FUZZEL MENU - WALLPAPER   ###
###################################


# Include general config
include=~/.config/fuzzel/fuzzel.ini


# Add/Override elements #
[main]
message="Wallpaper Selection"
match-counter=yes
#minimal-lines=yes
prompt="󰉔  "

